name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */6 * * *'    # Setiap 6 jam
  workflow_dispatch:          # Bisa dijalankan manual juga

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "haidarrdn@gmail.com"

      - name: Update dashboard.py dummy line
        run: |
          echo "# keep awake $(date)" >> dashboard.py
          git add dashboard.py
          git commit -m "Keep awake: update dashboard.py with dummy line"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
